# Generated by Django 2.2.7 on 2020-01-23 08:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('infrastuktura_wojskowa_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baza',
            name='adres',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='infrastuktura_wojskowa_app.Adres'),
        ),
    ]
