# Generated by Django 2.2.7 on 2020-01-23 08:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('infrastuktura_wojskowa_app', '0002_auto_20200123_0956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personel',
            name='pododdzial',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='infrastuktura_wojskowa_app.Pododdzial'),
        ),
        migrations.AlterField(
            model_name='personel',
            name='stopien',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='infrastuktura_wojskowa_app.Stopien'),
        ),
    ]
